### ISSUE TITLE
Boolean filters support

### ISSUE THREAD

**Issue by visheshd** [benhutchins/dyngoose#130]
https://github.com/benhutchins/dyngoose/blob/master/src/query/filters.ts#L7

I see this line commented just wanted to check if this is in the roadmap? or is it simply a matter uncommenting and adding AND and NOT?

**Comment by benhutchins** [comment]
The AND operator is already supported, since each specified filter concats with an AND.

There OR operator is on the roadmap, a lot of the work is there, but formatting the queries and making it easy to work with using the Dyngoose models is a bit complicated. I’ve had a need for it so I will likely get to it soon.

Not operators work by the not type. There are not exists, not null, etc. This is to ensure good typing is still available for each operator.

But your title says Boolean filters, which filtering by Booleans works as well. If you have a Boolean property on your model, you can filter by that as well.
