### ISSUE TITLE
Class members containing attribute type as @Dyngoose.Attribute.Any are not showing up in query records 

### ISSUE THREAD

**Issue by priyanshu966106** [benhutchins/dyngoose#417]
Class members containing attribute type as @Dyngoose.Attribute.Any are not showing up in query records 

```
Class abc {

@Dyngoose.Attribute.Any({ default: () =>{} })
  filecontents: ISomeObjectType;

}
```

when queried abc.someindexkey.query(....)  all fields except this are coming also its avaliable to the index name

**Comment by benhutchins** [comment]
Defaults apply on the record creation when using `MyTable.new` only.

It doesn't apply retroactively when records are queried from the table. Doing so can cause problems, if your query had a projection and didn't load that attribute, the default could apply incorrectly.

**Comment by priyanshu966106** [comment]
No not a default value problem i tried after removing it , also used different index even the field is not visible in the db queries using the primarykey index , and this works well while using the dynamo client from aws-sdk

**Comment by benhutchins** [comment]
Could you upload the entire class? I can't produce an error with a table containing an Any attribute.

**Comment by benhutchins** [comment]
@priyanshu966106 Just following up on this, are you able to provide a more complete example of the problem?

It sounds like it might be that you are trying to query by fields within the `Any`, but `Any` stores the value as JSON-encoded string and not as a native DynamoDB structure. For that, you can use `Dyngoose.Attribute.Map`, which currently requires a defined structure. 

```typescript
interface ITestMap {
  first: string
  middle: string
  last: string
  level: number
  nick?: string
}

class Table… {
  @Dyngoose.Attribute.Map({
    attributes: {
      first: Dyngoose.Attribute.String(),
      middle: Dyngoose.Attribute.String(),
      last: Dyngoose.Attribute.String(),
      level: Dyngoose.Attribute.Number(),
      nick: Dyngoose.Attribute.String(),
    },
  })
  public person: ITestMap
}
```

I've considered adding an alternative to `Any` that stores in native DynamoDB objects, without the need to define the expected object properties, however, it'll lose all typing benefits that Dyngoose attempts to provide.

I'm not sure if I understand the issue though, so if you can clarify that would be appreciated. If not, I'll close this ticket in a week due to inactivity.

**Comment by priyanshu966106** [comment]
Yes was trying to query on body but , without it too it doesn't returns anything for any field can,t use map as is a lot random data @benhutchins will create a demo repo and will try to provide you an example soon
