### ISSUE TITLE
Storing empty strings

### ISSUE THREAD

**Issue by akhader-mc** [benhutchins/dyngoose#480]
I noticed that it's not possible to assign a blank value to a table property. Now that DynamoDB does support blank values for non-key attributes: https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-dynamodb-now-supports-empty-values-for-non-key-string-and-binary-attributes-in-dynamodb-tables/#:~:text=May%2018%2C%202020-,Amazon%20DynamoDB%20now%20supports%20empty%20values%20for%20non-key%20String,before%20sending%20them%20to%20DynamoDB.

Is there something on the roadmap to support the same via dyngoose?

**Comment by benhutchins** [comment]
I hadn’t had it on the roadmap, but I could add it to it. What’s the use case for wanting to store empty values?

I know of a few possible use cases, but I think it might make querying difficult. Currently with the way dynamodb and dyngoose works, if I set an attribute to an empty value it actually gets deleted. Dyngoose doesn’t currently set values it null, instead it deletes the attribute entirely. This was a decision to simplify querying. You can usually be confident the attribute will not exist, so you can query for records where the attribute doesn’t exist rather than having to query for where it’s null, empty, or possibly doesn’t exist.

Dyngoose does support getters and setters for attributes as well, so if an attribute doesn’t exist and therefore the attribute value comes back as `null` you can use a getter to manipulate the read value and return a default or an empty object or similar depend ingredients on your use case.

I’m interested to hear what your use case is to see where this should fall on the roadmap.

**Comment by benhutchins** [comment]
Due to the lack of activity here I am going to close this. If you end up coming up with specific use cases please let me know and I can reopen to continue the discussion.
