### ISSUE TITLE
StringSet looks like not implemented.

### ISSUE THREAD

**Issue by air2** [benhutchins/dyngoose#633]
Does the stringset attribute misses the following in it's implementation?
  toDynamo(values: Value): DynamoDB.AttributeValue
  fromDynamo(value: DynamoDB.AttributeValue): Value | null 

I see this is done in the NumberSet but not in the StringSet and stringset does not seem to work correctly. Also I would suggest not to use string[] but Set<string> but I guess that is a different ticket.

**Comment by benhutchins** [comment]
StringSet is fully implemented, is there something you're seeing that isn't working when creating a StringSet attribute?

**Comment by air2** [comment]
Yes, 


when when I retrieve a record `await JobTable.primaryKey.get({ id })`

the

**Comment by benhutchins** [comment]
@air2 I think the issue here is the default value? You are setting the value to `[]` (an empty array), however, that default value will be ignored as the getter/setter properties set by the decorator will override it.

Dyngoose ensures all empty attribute values report as `null` and are removed from the record in DynamoDB. It never sets a value to a `NULL` type.

In this case, reading a value where `dismissed` is not set will return `null`. If you'd like to default to an empty array, you can do this with the `manipulateRead` method like:

```
  @Dyngoose.Attribute.StringSet({ manipulateRead: (val) => val ?? [] })
  public dismissed:string[] = []
```

I agree that the next version of Dyngoose should use a `Set` type instead of a native array. There is a utility `updateSet` on the table just because of this poor implementation.
