### ISSUE TITLE
empty StringSet is returned as empty object, instead of empty array

### ISSUE THREAD

**Issue by iwpnd** [benhutchins/dyngoose#667]
Hey there 👋 

whenever I find time I update dyngoose in my services. Most of the time that is a smooth transition after you cleared up #659 for me. Thank you again for the new version. 🙏 

Now I'm encountering an odd behaviour during one of those updates with the latest 4.1.1 version.

```typescript
import { Dyngoose } from 'dyngoose';
import { v4 as uuid } from 'uuid';

enum Types {
    FOO = "foo",
    BAR = "bar",
}

@Dyngoose.$Table({
    name: 'baguette',
})
export class BasicTable extends Dyngoose.Table {
    @Dyngoose.Attribute.String({ default: () => uuid() })
    public id: string;

    @Dyngoose.Attribute.StringSet()
    public types: `${Types}`[] | null;

    @Dyngoose.Attribute.Date({ nowOnCreate: true })
    public createdAt: string;

    @Dyngoose.Attribute.Date({ nowOnUpdate: true })
    public updatedAt: string;

    @Dyngoose.$PrimaryKey('id')
    static readonly pkId: Dyngoose.Query.PrimaryKey<BasicTable, string, string>;
}
```

In my example, if I do not create a row with `types` and fetch that row, the `types` attribute is `{}` where I would expect `null` or `undefined` as in `<v4`.

Is there chance you can help me figure out whether this is on Dyngoose or aws-sdk-v3?

edit:

As far as I could find out, Dyngoose does the right thing [here](https://github.com/benhutchins/dyngoose/blob/e1a53758c72389d1a21fe83af05b1f9444f4f91a/src/decorator/attribute-types/string-set.ts#L31) if I'm not mistaken.

**Comment by benhutchins** [comment]
Hey @iwpnd!

With Dyngoose v4, sets need to be a `Set` instance. This is native JavaScript object that ensures a value in the set may only occur once, removing the need for a lot of logic that was thrown in to ensure set arrays are unique and thereby Dyngoose no longer needs to mutate your sets directly.

Which means, every set needs to be specified as a Set.

```typescript

@Dyngoose.Attribute.StringSet()
public types: Set<`${Types}`>
```

As DynamoDB does not support saving empty sets, or really empty values in general, so Dyngoose still does prevent any attempts to save an empty values or sets.

When reading an attribute that does not exist on a document or that is a `NULL` type, you will get a `null` when reading an attribute. This should be the same behavior for string sets as with all attributes.

You may be seeing `{}` when you have a value and Dyngoose returns a `Set` object. Sets can be a bit odd when logging values, it will display `{}`. Using `util.inspect` may help you here, it will log the value type and in the case of sets, if the set has entries.

```typescript
import { inspect } from 'util'

const record = BasicTable.new()
console.log('should be null', inspect(record.types))

record.types = new Set(['foo', 'bar'])
console.log('should be a set', inspect(record.types))
```

Dyngoose does not retainyour set instance, so every time you read the property `types` you get a new `Set` instance. This was a feature historically, as it keeps all values stored as DynamoDB attribute maps and will transform values from there for you. Now with sets, this is a bit strange and I rework this further in the next Dyngoose release so set utility methods can be used to transform and Dyngoose could intelligently update sets using update operators rather than sending the entire set back to DynamoDB (important for situations where there are very large sets; this is something I have been working towards to better support Map and List types as well).

**Comment by iwpnd** [comment]
I see, thank you very much to take the time to write this up. Much appreciated.🙏🏻 

I think the docs threw me off here where it states a StringSet is an `string[]` type. But with your explanation it makes it clear. The Set in the name should've given it away tho. 🙂

So in my case I would be best served to use `Attributes.List()` instead if all I wanted was an array of strings.

**Comment by iwpnd** [comment]
Is there a way for me to ease this migration with this particular disparity of `List` and `StringSet` in mind?

If I have an existing table with a column that uses a `Attribute.StringSet()` in Dyngoose v3 I cannot just switch to `List()` and be done. 
I'm aware that I have to treat the `Set` differently throughout the application, this is not the issue. It's rather that the table already has a `StringSet` column I cannot just recreate and repopulate.

It also appears I can no longer perform `contain()` filters on a `StringSet`.

```typescript
 query.filter('types').contains('foo'); 
// Argument of type 'string' is not assignable to parameter of type 'Set<"foo","bar">
```

same for `includes()`

```typescript
 query.filter('types').includes('foo'); 
// Argument of type 'string' is not assignable to parameter of type 'Set<"foo","bar">
```

Do you see any way to optionally keep the old behaviour of `StringSet` 's to ease the transition?

**Comment by benhutchins** [comment]
To ease this, I've added a new option on sets to maintain the legacy arrays.

```typescript
@Dyngoose.Attribute.StringSet({ array: true })
myProperty: string[]
```

You'll need to add `array: true` to all the properties you have now, but it'll ensure values are not transformed to sets which should allow your code to operate as it was. The one exception is the utility method `updateSet` is still removed.

**Comment by iwpnd** [comment]
you're the best 🙏🏻

looking forward to giving this a try

**Comment by benhutchins** [comment]
I have pushed another update to improve searching for sets.

To note, you cannot use `includes` on a set with DynamoDB, you'd use `contains` on a set. It's a particularly confusing naming choice I made I have regretted for awhile, but includes actually uses the `IN` operator:

> a IN (b, c, d) — true if a is equal to any value in the list — for example, any of b, c or d. The list can contain up to 100 values, separated by commas.

Where contains uses `contains`:

```
True if the attribute specified by path is one of the following:

    A String that contains a particular substring.

    A Set that contains a particular element within the set.

    A List that contains a particular element within the list.

The operand must be a String if the attribute specified by path is a String. If the attribute specified by path is a Set, the operand must be the set's element type.

The path and the operand must be distinct; that is, contains (a, a) returns an error.

Example: Check whether the Brand attribute contains the substring Company.

    contains (Brand, :v_sub)

The expression attribute value :v_sub is a placeholder for Company.

Example: Check whether the product is available in red.

    contains (Color, :v_sub)

The expression attribute value :v_sub is a placeholder for Red.```

Source: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html
